# Generated by Django 5.1.6 on 2025-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0002_account_confirm_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="birth_date",
            new_name="birth_day",
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="subscribe",
            field=models.BooleanField(
                default=False, verbose_name="Subscribe to our newsletter"
            ),
        ),
    ]
