# Generated by Django 5.1.6 on 2025-03-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0003_rename_birth_date_account_birth_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
